# Site settings
title: Phong D. Vo
email: phong.vodinh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Personal homepage and microblogging 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "vodp.github.io" # the base hostname & protocol for your site
github_username:  vodp

# Build settings
markdown: kramdown
comments: true
