# Site settings
title: D.P Vo
email: phong.vodinh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Personal homepage  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "vodp.github.io" # the base hostname & protocol for your site
twitter_username: vo_d_p
github_username:  vodp

# Build settings
markdown: kramdown
comments: true
